
DROP TABLE tb_keymap;
CREATE TABLE tb_keymap 
( 
id INT NOT NULL AUTO_INCREMENT,
access_code VARCHAR(256) NOT NULL,
api_key VARCHAR(256) NOT NULL,
api_key_name VARCHAR(256) DEFAULT NULL,
used INT DEFAULT 1,
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);
DROP TABLE tb_appmetrics;
CREATE TABLE tb_appmetrics
( 
id INT NOT NULL AUTO_INCREMENT,
metric_name VARCHAR(256) NOT NULL,
used INT DEFAULT 1,
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);


DROP TABLE tb_dashboard;
CREATE TABLE tb_dashboard
(
dashboard_id INT NOT NULL AUTO_INCREMENT,
total_count INT DEFAULT NULL,
start_time DATETIME DEFAULT NULL,
finish_time DATETIME DEFAULT NULL,
start_time_file_code VARCHAR(32) DEFAULT NULL,
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (dashboard_id)
);

DROP TABLE tb_accesscode;
CREATE TABLE tb_accesscode
(
accesscode_id INT NOT NULL AUTO_INCREMENT,
dashboard_id INT NOT NULL ,
access_code VARCHAR(256) NOT NULL,
start_time DATETIME DEFAULT NULL,
finish_time DATETIME DEFAULT NULL,
total_count INT DEFAULT NULL,
running_status VARCHAR(32) DEFAULT NULL,
source_uri VARCHAR(1024) DEFAULT NULL,
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (accesscode_id)
);


DROP TABLE tb_apikey;
CREATE TABLE tb_apikey
(
apikey_id INT NOT NULL AUTO_INCREMENT,
accesscode_id INT NOT NULL ,
apikey VARCHAR(256) NOT NULL,
NAME VARCHAR(256) DEFAULT NULL,
start_time DATETIME DEFAULT NULL,
finish_time DATETIME DEFAULT NULL,
total_count INT DEFAULT NULL,
running_status VARCHAR(32) DEFAULT NULL,
filename VARCHAR(1024) DEFAULT NULL,
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (apikey_id)
);

DROP TABLE tb_api;
CREATE TABLE tb_api
(
api_id INT NOT NULL AUTO_INCREMENT,
apikey_id INT NOT NULL,
api VARCHAR(256) NOT NULL,
start_time DATETIME DEFAULT NULL,
finish_time DATETIME DEFAULT NULL,
elapsed INT DEFAULT NULL,
running_status VARCHAR(32) DEFAULT NULL,
uri VARCHAR(1024) DEFAULT NULL,
req_url VARCHAR(1024) DEFAULT NULL,
retry_count INT DEFAULT 0,
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (api_id)
);
